app/models.py
from datetime import datetime
from app import db

class Reviews(db.Model):
    # Table name
    __tablename__ = 'reviews'

    """
    -- Columns and constraints --
    Overall rating (5stars)
    Overall rating (Description - Tell us about your overall university experience so far.)
    Job prospects (5stars)
    Job prospects (Description - How does your uni make efforts to increase your employability (careers department, work placements, transferable skills)?)
    Course and lecture (5 stars)
    Course and lecture (Description - What do you like most and least about the way your course(s) are taught?)
    Uni Facilities (5 stars)
    Uni Facilities (Description - How good are your university's facilities?)
    Student Support (5 stars)
    Student Support (Description - How good is the support offered by the uni? Think both academic (tutors/feedback) and personal (counselling, etc).)
    Local life (5 stars)
    Local life (Description - How good is the local life in your city?)
    """
    id = db.Column(db.Integer, primary_key=True)
    course = db.Column(db.Text(), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    overall_rating = db.Column(db.Integer, nullable=False)
    job_prospects_rating = db.Column(db.Integer, nullable=False)
    job_prospects_desc = db.Column(db.Text(), nullable=True)
    course_lecturer_rating = db.Column(db.Integer, nullable=False)
    course_lecturer_desc = db.Column(db.Text(), nullable=True)
    facilities_rating = db.Column(db.Integer, nullable=False)
    facilities_desc = db.Column(db.Text(), nullable=True)
    student_support_rating = db.Column(db.Integer, nullable=False)
    student_support_desc = db.Column(db.Text(), nullable=True)
    local_life_rating = db.Column(db.Integer, nullable=False)
    local_life_desc = db.Column(db.Text(), nullable=True)
    
    # Constructor
    def __init__(self, course, date, overall_rating, job_prospects_rating, job_prospects_desc,
                 course_lecturer_rating, course_lecturer_desc, facilities_rating, facilities_desc,
                 student_support_rating, student_support_desc, local_life_rating, local_life_desc):
        self.course = course
        self.date = date
        self.overall_rating = overall_rating
        self.job_prospects_rating = job_prospects_rating
        self.job_prospects_desc = job_prospects_desc
        self.course_lecturer_rating = course_lecturer_rating
        self.course_lecturer_desc = course_lecturer_desc
        self.facilities_rating = facilities_rating
        self.facilities_desc = facilities_desc
        self.student_support_rating = student_support_rating
        self.student_support_desc = student_support_desc
        self.local_life_rating = local_life_rating
        self.local_life_desc = local_life_desc
    
    def __repr__(self):
        return (f"Review('{self.course}', '{self.date}', '{self.overall_rating}', '{self.job_prospects_rating}', "
                f"'{self.job_prospects_desc}', '{self.course_lecturer_rating}', '{self.course_lecturer_desc}', '{self.facilities_rating}', "
                f"'{self.facilities_desc}', '{self.student_support_rating}', '{self.student_support_desc}', '{self.local_life_rating}', {self.local_life_desc}')")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from app.config import Config

app = Flask(__name__)

db = SQLAlchemy()
    
def create_app(config_class=Config):
    # Apply all configuration in the config.py file to the app
    app.config.from_object(config_class)
    
    # Pass in app for our extensions above this class
    db.init_app(app)
    
    # Used to create the tables in the database
    # with app.app_context():
    #     db.create_all()
    
    # import 'main' is the blueprint instance we made at start of main.routes files
    from app.main.routes import main
    from app.errors.handlers import errors
    
    # Need to register our blueprint before we can use it in our actual app
    app.register_blueprint(main)
    app.register_blueprint(errors)
    
    return app

app/main/__init__.py
'''
__init__.py files dont have to have anything in them, but shows python
that the directory __init__.py is in, should be treated as a package.
In this case 'main' is a package.
'''

app/main/routes.py
from flask import render_template, Blueprint, request
from app.models import Reviews

main = Blueprint('main', __name__, template_folder='../templates', static_folder='../static')
    
# Home page
@main.route("/")
@main.route("/home")
def index():
    
    # Grab 3 featured reviews, which are the most recent 5 star reviews
    posts = Reviews.query.filter_by(overall_rating=5).order_by(Reviews.date.desc()).limit(3)
    
    return render_template("index.html", reviews=posts)

# Reviews page
latest_posts = True    # Flag to check if we need to grab the latest posts
setup = True    # Flag to check if we need to setup the filter course dropdown
courses = ['ALL']    # List of all courses to allow user to filter by course
current_course_filter = 'ALL'    # Current course filter

@main.route("/reviews", methods=['GET', 'POST'])
def reviews():
    # Need to make this global so we can change it in the function
    global latest_posts, setup, current_course_filter
    
    # Paginate / Pagination is where we split items (posts/reviews) into separate pages for readability
    # and also to prevent longer loading times for each page
    page = request.args.get('page', 1, type=int)    # default 1
    
    # Get our initial posts
    posts = Reviews.query.order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
    
    # Grab 5 posts per page (default)
    if latest_posts:
        if current_course_filter != 'ALL':    # If we have a course filter then filter by that
            posts = Reviews.query.filter_by(course=current_course_filter).order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
        else:
            posts = Reviews.query.order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
    else:
        if current_course_filter != 'ALL':
            posts = Reviews.query.filter_by(course=current_course_filter).order_by(Reviews.date.asc()).paginate(page=page, per_page=5)
        else:
            posts = Reviews.query.order_by(Reviews.date.asc()).paginate(page=page, per_page=5)
    
    # Check if we receive a POST request
    if request.method == "POST":
        if request.form.get("latest"):
            if current_course_filter != 'ALL':
                posts = Reviews.query.filter_by(course=current_course_filter).order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
            else:
                posts = Reviews.query.order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
            latest_posts = True
        elif request.form.get("oldest"):
            if current_course_filter != 'ALL':
                posts = Reviews.query.filter_by(course=current_course_filter).order_by(Reviews.date.asc()).paginate(page=page, per_page=5)
            else:
                posts = Reviews.query.order_by(Reviews.date.asc()).paginate(page=page, per_page=5)
            latest_posts = False
        elif request.form.get("course_select"):
            course_selection = request.form.get('course_select')
            current_course_filter = course_selection    # Update the current course filter
            
            if course_selection == 'ALL':    # If we select 'ALL' then we want to grab all posts
                posts = Reviews.query.order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
            else:
                posts = Reviews.query.filter_by(course=course_selection).order_by(Reviews.date.desc()).paginate(page=page, per_page=5)
    
    # Check if we need to setup the filter course dropdown
    if setup:
        for value in Reviews.query.distinct(Reviews.course):    # Grab all unique courses
            courses.append(value.course)
        setup = False
    
    return render_template("reviews.html", reviews=posts, courses=courses)

# Data insights page
@main.route("/insights")
def insights():
    return render_template("insights.html")

# Conclusions page
@main.route("/conclusions")
def conclusions():
    return render_template("conclusions.html")

app/templates/conclusions.html
<!-- Conclusions page html, this automatically extends everything form layout.html -->
{% extends "layout.html" %}
{% block content %}
    <title>Conclusion</title>
    <div class="conclusion-container">
        <div class="conclusion-text">
            <h1>Conclusion</h1>
            <p> This website is a product a of Level 2 University Assessment made by Computer
                Science students for the University of Lincoln as part of the Team Software
                Engineering module. We hope that this website has given you a good insight
                into the thoughts and feelings of University of Lincoln students past and present.
            </p>
            <p> The data we scraped from
                <a href="https://www.whatuni.com/university-course-reviews/university-of-lincoln/">What Uni?</a>
                ranges from beginning 2018 to the present.
                This gives us confidence that the data on this website is not out-dated while
                giving us a large enough window for a diverse set of opinions. One of the reasons
                this is especially important is because our timeframe encompasses the largest
                worldwide socioeconomic
                disruption seen this century, with the COVID-19 pandemic. This means that our
                results from March 2020 to at least December 2021, if not the present, will be
                skewed. This especially leaves gaps in the 2020-2021 timeframe in which time
                students did not submit as many reviews. In contrast reviews submitted in 2019
                make up a large majority of our dataset.
            </p>
            <p> As for the data we collected through our survey; that too had a few obstacles
                we had to overcome. The first issue was that we were collecting data by
                forwarding the survey to fellow students. This in turn means we will largely
                only get data based on students who have not yet graduated. This greatly
                diminishes our range as it might not include pre-pandemic opinions when
                attending the university might be more normal and consistent. As well as
                this the main avenue for survey distribution was relaying it to friends
                and colleagues. The issue with that being that these people are likely
                to be fellow Computer Science students which would lead to a biased dataset
                as well as a dataset lacking diversity. We tried to actively avoid posting
                the survey in any digital groups that were based around a particular course.
            </p>
            <p> Overall all the opinions of the students were positive. To make the results
                easily readable we included a star-based rating system into our website.
                The mean averages for all five category ratings were all at or above 4 out of 5.
                Not only were students pleased with the given categories, the overall university
                satisfaction rating followed a similar pattern of being above 4 stars. This 4 star-based
                rating was consistent between the four years.
            </p>

        </div>
    </div>
{% endblock content %}

app/templates/insights.html
<!-- Home page html, this automatically extends everything form layout.html -->
{% extends "layout.html" %}
{% block content %}
    <title>Insights</title>

    <!-- Data analytics visualizations -->
    <div style="text-align: center;justify-content: center; padding-top: 30px;">
        <h4>Data visualizations</h3>
    </div>
    
    <!-- Data viz embedded charts from plotly -->

    <div class="plotly-charts">
        <div class="charts">
            <iframe frameborder="0" scrolling="no" src="//plotly.com/~mathewsjoyy/3.embed?logo=false&link=false&autosize=true"></iframe>
        </div>
        <div class="charts">
            <iframe frameborder="0" scrolling="no" src="//plotly.com/~mathewsjoyy/1.embed?logo=false&link=false&autosize=true"></iframe>
        </div>
    </div>

    <div class="plotly-charts2">
        <div class="charts2">
            <iframe frameborder="0" scrolling="no" src="//plotly.com/~mathewsjoyy/8.embed?logo=false&link=false&autosize=true"></iframe>
        </div>
    </div>

    <div class="plotly-charts">
        <div class="charts">
            <img src="{{url_for('static', filename='images/good-wordcloud.png')}}" alt="Word Cloud Positive" >
        </div>
        <div class="charts">
            <img src="{{url_for('static', filename='images/bad-wordcloud.png')}}" alt="Word Cloud Negative-Neutral">
        </div>
    </div>

    <hr>

    <section id="data-comments-section" class="container mb-3">
        <div class="row">
            <div class="col-md-12">
                <div class="section-header">
                    <h4>Data Conclusions</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>
                    The original aim for the visualizations was to provide a more easy to understand and easily interpretable look at the overall university
                    review data. Essentially allowing a graphical summary of different parts of the data, such as the overall rating for the University of Lincoln
                    over the previous years. However, it was soon found after basic data analysis that the data was limited in the visualizations able to be derived from it.
                </p>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <h4>Dataset Limitations and Considerations</h4>
                <p>
                    <li>
                        <code>
                            <table style="width: 250px;float: left;">
                                <tr>
                                  <th>Year</th>
                                  <th>No. Reviews</th>
                                </tr>
                                <tr>
                                  <td>2022</td>
                                  <td>40</td>
                                </tr>
                                <tr>
                                  <td>2021</td>
                                  <td>23</td>
                                </tr>
                                <tr>
                                  <td>2020</td>
                                  <td>133</td>
                                </tr>
                                <tr>
                                  <td>2019</td>
                                  <td>309</td>
                                </tr>
                                <tr>
                                  <td>2018</td>
                                  <td>122</td>
                                </tr>
                                <tr>
                                  <td>2017</td>
                                  <td>93</td>
                                </tr>
                              </table>
                        </code>
                        There is a heavy amount of reviews in 2019 but very little in 2022 and 2021
                        This is important to keep in mind during analysis, as when creating visualizations comparing the data from different years,
                        e.g. mean overall rating for the University of lincoln from 2017 - 2022, having more reviews in 2019 will result in a more accurate mean rating. However,
                        for years such as 2022 and 2021, there is a lot less, so the visualizations will be less accurate to the true student experience.
                    </li>
                    <br><br><br>
                    <li>
                        When creating visualizations comparing the different courses at Lincoln ("Mean overall rating for courses from the University of Lincoln"),
                        it was found this visualization initially wasn't very effective as many courses have only 1 or few reviews compared to other courses
                        that have many. This can impact the plot as you may have 1 course with 1 review of 5 stars, resulting in a mean
                        of 5, however in actual fact the course might not be great and is being skewed by the view of 1 person.
                        This limitation/issue was combatted by displaying the number of reviews for each course when you hover over the course on the chart.
                    </li>
                    <br>
                    <li>
                        A final limitation when performing analysis on our data was the high amount of non-quantitative data (text based). Although this form of
                        data helps provided greater insights into the university experience, it provides little value in the visualizations. That is why we decided to create 2
                        word clouds a thumbs up and thumbs down shaped one. The thumbs up word cloud is created using the reviews with a overall rating of 4 or higher, and the thumbs down
                        word cloud is created using the reviews with a overall rating of less then 2.
                    </li>
                </p>
            </div>
        </div>
    </section>

{% endblock content %}

app/templates/layout.html
<!-- Layout file, that all other html files can extend from -->
<!-- Contains the bare basics, such as header, footer etc. -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <meta name="description" content="Artefact produced by Group 10 from the University of Lincoln, to show the analysis of University related data">
    <meta name="author" content="TSE Group 10">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/2b30f58ae7.js" crossorigin="anonymous"></script>

    <!--icon packages-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Jquery and Jquery UI-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

</head>
<body>

    <!-- Navigation Bar -->
    <header class="site-header">
        <nav class="navbar navbar-expand-lg py-4 navbar-light bg-light ">
            <div class="container">
            <a href="{{ url_for('main.index')}}" class="navbar-brand">Lincoln Student Reviews</a>
            <img class="navbar-brand" src="{{ url_for('static', filename='images/site-logo.png')}}" style="width:70px; height:75px;" alt="Lincoln University Logo">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <div class="navbar-nav mr-auto">
                </div>
                <!--Right side-->
                <div class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.reviews')}}">Reviews</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.insights')}}">Data Insights</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.conclusions')}}">Conclusions</a>
                    </li>
                </div>
            </div>
            </div>
        </nav>
        <hr>
    </header>


    <!-- Other html docs that inherit this doc will insert there content in here-->
    {% block content %}{% endblock %}

    <!--Scroll to top button-->
    <button id="btnScrollToTop">
        <i class="material-icons">arrow_upward</i>
    </button>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Custom Javascript file -->
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>

</body>
</html>

app/templates/reviews.html
<!-- Home page html, this automatically extends everything form layout.html -->
{% extends "layout.html" %}
{% block content %}
    <title>Reviews</title>

    <!-- Buttons to help filter reviews -->
    <div class="filter-buttons">
        <h5>Filter reviews</h5>
        <form action="{{ url_for('main.reviews') }}" method="POST">
            <button type="submit" name="latest" value="latest" class="btn btn-primary btn-sm">Latest Reviews</button>
            <button type="submit" name="oldest" value="oldest" class="btn btn-primary btn-sm">Oldest Reviews</button>
            <br>
            <div class="course-filter pt-2">
                <span>Filter by course⠀</span>
                    <select name="course_select">
                        <option value="{{courses[0]}}" selected>{{courses[0]}}</option>
                        {% for c in courses[1:] %}
                        <option value="{{ c }}">{{ c }}</option>
                        {% endfor %}
                    </select>
                <button type="submit" class="btn btn-primary btn-sm">Go</button>
            </div>
        </form>
    </div>
    <hr>

    <section id="reviews">

        <div class="review-box-container">
            <!-- Get all the data from postgres database-->
            {% for review in reviews.items %}
                <div class="review-box">
                    <div class="box-top">

                        <div class="profile">
                            <div class="profile-img">
                                <img src="{{ url_for('static', filename='images/Lincoln-Logo.png') }}" width="50" height="50" alt="profile">
                            </div> 
                            <div class="name-user">
                                <strong>{{ review.course }}</strong>
                                <span> {{ review.date.strftime('%Y-%m-%d') }}</span>
                            </div>
                        </div>
                        
                        <!-- Overall rating star display-->
                        {% if review.local_life_rating > 0 %}
                            <div class="review-content">
                                <b>Overall Rating</b>
                                {% for x in range(0, review.overall_rating) %}
                                    <i class="fas fa-star" style="color:yellow; text-shadow: 0 0 5px #000;"></i>
                                {% endfor %}
                                {% for x in range(0, 5 - review.overall_rating) %}
                                    <i class="far fa-star"></i> <!-- Holo star -->
                                {% endfor %}
                            </div>
                        {% endif %}
                        
                        <!-- Job prospects rating -->
                        {% if review.local_life_rating > 0 %}
                            <div class="review-content">
                                <b>Job Prospects</b>
                                {% for x in range(0, review.job_prospects_rating) %}
                                    <i class="fas fa-star" style="color:yellow; text-shadow: 0 0 5px #000;"></i>
                                {% endfor %}
                                {% for x in range(0, 5 - review.job_prospects_rating) %}
                                    <i class="far fa-star"></i>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <!-- Course lecturer rating -->
                        {% if review.local_life_rating > 0 %}
                            <div class="review-content">
                                <b>Course & Lecturer</b>
                                {% for x in range(0, review.course_lecturer_rating) %}
                                    <i class="fas fa-star" style="color:yellow; text-shadow: 0 0 5px #000;"></i>
                                {% endfor %}
                                {% for x in range(0, 5 - review.course_lecturer_rating) %}
                                    <i class="far fa-star"></i>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <!-- Facilities rating -->
                        {% if review.local_life_rating > 0 %}
                            <div class="review-content">
                                <b>Facilities</b>
                                {% for x in range(0, review.facilities_rating) %}
                                    <i class="fas fa-star" style="color:yellow; text-shadow: 0 0 5px #000;"></i>
                                {% endfor %}
                                {% for x in range(0, 5 - review.facilities_rating) %}
                                    <i class="far fa-star"></i>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <!-- Student Support rating -->
                        {% if review.local_life_rating > 0 %}
                            <div class="review-content">
                                <b>Student Support</b>
                                {% for x in range(0, review.student_support_rating) %}
                                    <i class="fas fa-star" style="color:yellow; text-shadow: 0 0 5px #000;"></i>
                                {% endfor %}
                                {% for x in range(0, 5 - review.student_support_rating) %}
                                    <i class="far fa-star"></i>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <!-- Local Life rating -->
                        {% if review.local_life_rating > 0 %}
                            <div class="review-content">
                                <b>Local Life</b>
                                {% for x in range(0, review.local_life_rating) %}
                                    <i class="fas fa-star" style="color:yellow; text-shadow: 0 0 5px #000;"></i>
                                {% endfor %}
                                {% for x in range(0, 5 - review.local_life_rating) %}
                                    <i class="far fa-star"></i>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    
                    <div class="content hideContent">
                        {% if review.course_lecturer_desc != "N/A"%}
                            <b>What do you like/dislike about the way your course and lecturers? (How is the course teaching balance?)</b>
                            <p>{{review.course_lecturer_desc}}</p>
                        {% endif %}

                        {% if review.facilities_desc != "N/A" %}
                            <b>How are your university's facilities? what can be improved?</b>
                            <p>{{review.facilities_desc}}</p>
                        {% endif %}

                        {% if review.student_support_desc != "N/A"%}
                            <b>How good is the support offered by the uni?</b>
                            <p>{{review.student_support_desc}}</p>
                        {% endif %}

                        {% if review.job_prospects_desc != "N/A"%}
                            <b>How does your uni make efforts to increase your employability?</b>
                            <p>{{review.job_prospects_desc}}</p>
                        {% endif %}
                        
                        {% if review.local_life_desc != "N/A"%}
                            <b>Is your university in a good location in terms of distance to accommodation and local amenities?</b>
                            <p>{{review.local_life_desc}}</p>
                        {% endif %}
                    </div>

                    <div class="show-more">
                        <a href="#/">Show more</a>
                    </div>

                </div>
            {% endfor %}
        </div>
    </section>


    <!--Page number nav bar-->
    <!--Loop through the page numbers -->
    <div id="pagebutton_container" class="pt-4">
        {% for page_num in reviews.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
            {% if page_num %} <!--If page num is not None give link to the page-->
            {% if reviews.page == page_num %} <!--If we on the current page then outline that button-->
                <a class="btn btn-primary mb-4" href="{{ url_for('main.reviews', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-primary mb-4" href="{{ url_for('main.reviews', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
            {% else %} <!--If page num is none then just put an ellipse-->
            ⠀...⠀
            {% endif %}
        {% endfor %}
    </div>
    
{% endblock content %}